services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mailgun-webhooks
      - PORT=3000
    depends_on:
      - mongodb
    volumes:
      - ./public:/usr/src/app/public
      - ./server:/usr/src/app/server
      - ./.env:/usr/src/app/.env
    command: npm run dev
    logging: &logging
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "1"

  mongodb:
    image: mongo:latest
    logging: *logging
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    logging: *logging
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      - mongodb

volumes:
  mongodb_data: 